# Generated by Django 2.0.4 on 2018-06-02 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('nickname', models.CharField(max_length=120)),
                ('birthday', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('height', models.PositiveIntegerField(help_text='Altura en cm')),
                ('weight', models.PositiveIntegerField(help_text='Peso en gramos')),
                ('position', models.CharField(choices=[('BA', 'Base'), ('ES', 'Escolta'), ('AL', 'Alero'), ('AP', 'Ala-pivot'), ('PI', 'Pivot')], max_length=60)),
                ('rut', models.CharField(max_length=8)),
                ('dv', models.PositiveIntegerField()),
                ('picture', models.ImageField(upload_to='picture_players')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='RosterSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Player')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Roster')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logos')),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basket.Coach')),
            ],
        ),
        migrations.AddField(
            model_name='rosterselection',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AddField(
            model_name='roster',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchroster_local', to='basket.Roster'),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basket.Match'),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchroster_visit', to='basket.Roster'),
        ),
        migrations.AddField(
            model_name='match',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_local', to='basket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_visit', to='basket.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='rosterselection',
            unique_together={('roster', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='matchroster',
            unique_together={('match', 'local', 'visit')},
        ),
    ]
