# Generated by Django 2.0.4 on 2018-06-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dv',
            field=models.CharField(max_length=1),
        ),
    ]
