# Generated by Django 2.0.4 on 2018-06-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20180424_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchRoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='RosterSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Player')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Roster')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='code',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='basket.Coach'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rosterselection',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchroster_local', to='basket.Roster'),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basket.Match'),
        ),
        migrations.AddField(
            model_name='matchroster',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchroster_visit', to='basket.Roster'),
        ),
        migrations.AddField(
            model_name='match',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_local', to='basket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_visit', to='basket.Team'),
        ),
    ]
