# Generated by Django 2.0.4 on 2018-06-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20180602_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='dv',
            field=models.CharField(max_length=1),
        ),
    ]
