# Generated by Django 2.0.4 on 2018-06-01 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_auto_20180601_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basket.Team'),
            preserve_default=False,
        ),
    ]
